<?php

declare(strict_types=1);

namespace App\Administering\ServiceInterface\Managing;

use App\Administering\Value\Managing\AdministrationManagingFieldVisibilityInspectionPrepareRequest;
use App\Administering\Value\Managing\AdministrationManagingFieldVisibilityInspectionPrepareResult;

interface AdministrationFieldVisibilityInspectionPrepareServiceInterface
{
    public function prepare(AdministrationManagingFieldVisibilityInspectionPrepareRequest $request): AdministrationManagingFieldVisibilityInspectionPrepareResult;
}
