doctrine:
  dbal:
    url: '%env(default:administering_standalone_database_url:DATABASE_URL)%'
  orm:
    auto_mapping: true
    mappings:
      Administering:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Administering\Entity'
        alias: Administering
