framework:
  secret: '%env(default:administering_standalone_secret:APP_SECRET)%'
  http_method_override: false
  handle_all_throwables: true
  session:
    enabled: false
  router:
    utf8: true
  php_errors:
    log: true
  messenger:
    transports:
      sync: 'sync://'
    routing:
      App\Administering\Message\AdministrationConfigurationScanMessage: sync
      App\Administering\Message\AdministrationOperationRunMessage: sync

parameters:
  administering_standalone_secret: 'administering-local-standalone-secret'
  administering_standalone_database_url: 'sqlite:///%kernel.project_dir%/var/standalone.db'
