security:
  providers:
    administering_standalone_memory_provider:
      memory: null
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: administering_standalone_memory_provider
  access_control: []
